### ISSUE TITLE
Package the project

### ISSUE THREAD

**Issue by ngarneau** [ngarneau/vecmap#32]
We need to deliver the datasets with the MD5 hash key.

**Comment by ngarneau** [comment]
More here: https://gitlab.com/CLARIN-ERIC/reprolang

**Comment by davebulaval** [comment]
Only missing the tag.

**Comment by davebulaval** [comment]
6. Tag a new release to trigger CI docker image creation
After tagging a new release in the gitlab.com repository, a CI/CD pipeline will be started, and upon pipeline's successfull completion, the final docker image will by pushed
to the docker image registry on gitlab.com.
