### ISSUE TITLE
Freeze an Experiment Framework

### ISSUE THREAD

**Issue by ngarneau** [ngarneau/vecmap#6]
Choose between MLFlow and Sacred.

We need to quickly add this framework to the codebase to track the results of the original repository of the paper before making any major change in the code.

These results will be used as the "baseline" of the paper.

**Comment by ngarneau** [comment]
We definitely need a configuration file. There are so many hyperparameters its a whole mess.

**Comment by davebulaval** [comment]
MLFlow est un recoupement de Keras et de tracking d'experiment. Il y a du automatic logging avec Keras. Il y a du tracking d'artificat (kinf od checkpoint)

C'est pas vraiment la même offre que Sacred, sauf que si on veux prendre MLflow, je pense que d'utiliser des frameworks comme poutyne va devenir inutile comme il fait déjà cette portion là.
